modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    namespace="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://github.com/Negodya1/Create-Vintage-Improvements"
    issueTrackerURL="https://github.com/Negodya1/Create-Vintage-Improvements/issues"
    logoFile="logo.png"
    credits='''Catchmons, Junnaturefox & Qi-Month - zh_cn localization
padin - en_us localization editing
reds - pt_br localization'''
    authors="${mod_authors}"
    #displayTest="MATCH_VERSION"

description="${mod_description}"

[[dependencies.mod_id]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.mod_id]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.modid]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.e,)"
    ordering="NONE"
    side="BOTH"